name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    container: python:3.11
    runs-on: ubuntu-latest
    steps:
      - run: cd ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python3 --version
      - run: pwd
      - run: ls
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."